-------------------------------------------------
-- Markdown files behavior
-------------------------------------------------
-- Enable auto save when leaving buffer (due to navigation or other stuff)
-- Doesn't work, global option
-- vim.bo.autowriteall = true
